import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import * as simpleIcons from 'simple-icons';
import type { SimpleIcon } from 'simple-icons';
import { slugToVariableName } from 'simple-icons/sdk';

import { simpleIconToSlugIcon } from '../src/simple-icons.ts';

const SLUGS: ReadonlyArray<{ readonly bromaidSlug: string; readonly simpleIconsSlug: string }> =
  [
    { bromaidSlug: 'gcp', simpleIconsSlug: 'googlecloud' },
    { bromaidSlug: 'github', simpleIconsSlug: 'github' },
    { bromaidSlug: 'cloudflare', simpleIconsSlug: 'cloudflare' },
    { bromaidSlug: 'keycloak', simpleIconsSlug: 'keycloak' },
    { bromaidSlug: 'posthog', simpleIconsSlug: 'posthog' },
    { bromaidSlug: 'intercom', simpleIconsSlug: 'intercom' },
    { bromaidSlug: 'tailscale', simpleIconsSlug: 'tailscale' },
    { bromaidSlug: 'coolify', simpleIconsSlug: 'coolify' },
    { bromaidSlug: 'nextjs', simpleIconsSlug: 'nextdotjs' },
    { bromaidSlug: 'redis', simpleIconsSlug: 'redis' },
    { bromaidSlug: 'datadog', simpleIconsSlug: 'datadog' },
    { bromaidSlug: 'stripe', simpleIconsSlug: 'stripe' },
  ];

function toTsStringLiteral(s: string): string {
  return JSON.stringify(s);
}

function renderGeneratedFile(
  iconsByBromaidSlug: ReadonlyMap<string, { readonly svg: string; readonly path: string }>,
): string {
  const entries = [...iconsByBromaidSlug.entries()].sort(([a], [b]) =>
    a.localeCompare(b),
  );

  const lines: string[] = [];
  lines.push('/* eslint-disable */');
  lines.push('/* This file is generated by scripts/generate-icons.ts */');
  lines.push("import type { SlugIcon } from './types.js';");
  lines.push('');
  lines.push(
    'export const generatedSlugIcons = Object.freeze({',
  );
  for (const [bromaidSlug, icon] of entries) {
    const slugIcon = simpleIconToSlugIcon(icon);
    lines.push(`  ${toTsStringLiteral(bromaidSlug)}: {`);
    lines.push(`    viewBox: ${toTsStringLiteral(slugIcon.viewBox)},`);
    lines.push('    paths: [');
    for (const p of slugIcon.paths) {
      lines.push(`      { d: ${toTsStringLiteral(p.d)} },`);
    }
    lines.push('    ],');
    lines.push('  },');
  }
  lines.push('} satisfies Readonly<Record<string, SlugIcon>>);');
  lines.push('');
  return lines.join('\n');
}

async function main(): Promise<void> {
  const out = new Map<string, { readonly svg: string; readonly path: string }>();
  for (const m of SLUGS) {
    const variable = slugToVariableName(m.simpleIconsSlug);
    const hit = (simpleIcons as Record<string, SimpleIcon | undefined>)[variable];
    if (hit === undefined) {
      throw new Error(
        `Simple Icons export not found: "${variable}" (slug "${m.simpleIconsSlug}", bromaid "${m.bromaidSlug}")`,
      );
    }
    out.set(m.bromaidSlug, { svg: hit.svg, path: hit.path });
  }

  const here = path.dirname(fileURLToPath(import.meta.url));
  const target = path.resolve(here, '../src/generated-icons.ts');
  const contents = renderGeneratedFile(out);
  await writeFile(target, contents, 'utf8');
}

main().catch((err: unknown) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exitCode = 1;
});

